# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: GrailMarket
description: Grail market crosschain indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
  - name: GrailMarket
    abi_file_path: ./abis/GrailMarketAbi.json
    handler: ./src/EventHandlers.ts
    events:
      - event: Bearish(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: Bullish(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: Settle(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 reward, bool isRefund)
      - event: CreateMarket(bytes32 indexed id, address creator)
      - event: SetMinStakeAmount(uint256 minStakeAmount)
      - event: NewRound(bytes32 indexed id, uint256 indexed roundId, uint256 openingTime, uint256 closingTime)
      - event: SetRoundPriceMark(bytes32 indexed id, uint256 indexed roundId, int256 priceMark, uint256 closingTime)
      - event: Resolve(bytes32 indexed id, uint256 indexed roundId, uint256 rewardPool, uint256 totalWinningStake, int256 closingPrice, uint256 winningSide)
      - event: CancelRound(bytes32 indexed id, uint256 indexed roundId)
      - event: SetMarketDuration(uint32 duration)
      - event: SetProtocolFee(uint16 newFee)
unordered_multichain_mode: true
networks:
  - id: 43113 # Avalanche Fuji
    start_block: 38187796
    contracts:
      - name: GrailMarket
        address: 0x359f3b29d5Ec17393d42717e9eA4704DFeFA60C2
  - id: 421614 # Arbitrum Sepolia
    start_block: 124996529
    contracts:
      - name: GrailMarket
        address: 0x359f3b29d5Ec17393d42717e9eA4704DFeFA60C2
  - id: 84532 # Base Sepolia
    start_block: 22064534
    contracts:
      - name: GrailMarket
        address: 0x359f3b29d5Ec17393d42717e9eA4704DFeFA60C2
  - id: 97 # Bsc Testnet
    start_block: 22064534
    contracts:
      - name: GrailMarket
        address: 0x359f3b29d5Ec17393d42717e9eA4704DFeFA60C2
  - id: 44787 # Celo Alfojores
    rpc_config:
      url: https://alfajores-forno.celo-testnet.org
    start_block: 22064534
    contracts:
      - name: GrailMarket
        address: 0x359f3b29d5Ec17393d42717e9eA4704DFeFA60C2
  - id: 11155111 # Ethereum Sepolia
    start_block: 22064534
    contracts:
      - name: GrailMarket
        address: 0x359f3b29d5Ec17393d42717e9eA4704DFeFA60C2
  - id: 11155420 # Optimism Sepolia
    start_block: 22064534
    contracts:
      - name: GrailMarket
        address: 0x359f3b29d5Ec17393d42717e9eA4704DFeFA60C2
  - id: 80002 # Polygon Amoy
    start_block: 22064534
    contracts:
      - name: GrailMarket
        address: 0x359f3b29d5Ec17393d42717e9eA4704DFeFA60C2
  - id: 1301 # Unichain Sepolia
    start_block: 22064534
    contracts:
      - name: GrailMarket
        address: 0x217dc94990C67885BA4b87CdBa345422376A9Ac3
# Rollback on reorg mode currently incurs a performance hit on historical sync
# while developing an indexer we recommend setting this to false
rollback_on_reorg: false
