# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: GrailMarket
description: Grail market indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
  - name: GrailMarket
    abi_file_path: ./abis/GrailMarketAbi.json
    handler: ./src/EventHandlers.ts
    events:
      - event: Bearish(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: Bullish(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: Settle(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 reward, bool isRefund)
      - event: CreateMarket(bytes32 indexed id, address creator)
      - event: SetMinStakeAmount(uint256 minStakeAmount)
      - event: NewRound(bytes32 indexed id, uint256 indexed roundId, uint256 lockTime, uint256 closingTime)
      - event: SetRoundPriceMark(bytes32 indexed id, uint256 indexed roundId, int256 priceMark, uint256 closingTime)
      - event: Resolve(bytes32 indexed id, uint256 indexed roundId, uint256 rewardPool, uint256 totalWinningStake, int256 closingPrice, uint256 winningSide, uint256 resolverReward)
      - event: CancelRound(bytes32 indexed id, uint256 indexed roundId)
      - event: SetMarketDuration(uint32 duration)
      - event: SetResolverFee(uint16 newFee)
      - event: SetProtocolFee(uint16 newFee)
unordered_multichain_mode: true
networks:
  # - id: 2741 # Abstract
  #   rpc_config:
  #     url: https://api.mainnet.abs.xyz
  #   start_block: 414268
  #   contracts:
  #     - name: GrailMarket
  #       address: 0xDCdf9C9A370EdE475D5d19C84E30625e80BDbCEd
  - id: 42161 # Arbitrum
    start_block: 338761118
    contracts:
      - name: GrailMarket
        address: 0x9C13F708FcDB955eD53497B6D107994EF6A02aed
  - id: 43114 # Avalanche
    start_block: 62406145
    contracts:
      - name: GrailMarket
        address: 0xd83ED35c12394030D90b9FA9F3769C99B64c274e
  # - id: 8453 # Base
  #   start_block: 29311407
  #   contracts:
  #     - name: GrailMarket
  #       address: 0x4A203f5Fc6AbDe7978A4A45531D0BE30678A3efB
  - id: 80094 # Berachain
    rpc_config:
      url: https://berachain-rpc.publicnode.com
    start_block: 5278771
    contracts:
      - name: GrailMarket
        address: 0x3D9e829E9c4018B05b1fe595f771c4D7346A989B
  - id: 81457 # Blast
    rpc_config:
      url: https://blast-rpc.publicnode.com
    start_block: 19480648
    contracts:
      - name: GrailMarket
        address: 0x1AeA0284F33846f7eF48f6962E45F175B28F4F92
  - id: 56 # BSC
    start_block: 50018521
    contracts:
      - name: GrailMarket
        address: 0x2b395241182f76a7C69f27D930e18599b12099Ea
  - id: 42220 # Celo
    rpc_config:
      url: https://forno.celo.org
    start_block: 35870498
    contracts:
      - name: GrailMarket
        address: 0xc72f677dD5dA318F371bF2dEDe335d75bF6E2513
  # - id: 1116 # CoreDao
  #   rpc_config:
  #     url: https://rpc.coredao.org
  #   start_block: 24036087
  #   contracts:
  #     - name: GrailMarket
  #       address: 0x4A203f5Fc6AbDe7978A4A45531D0BE30678A3efB
  # - id: 25 # Cronos
  #   rpc_config:
  #     url: https://cronos-evm-rpc.publicnode.com
  #   start_block: 19175923
  #   contracts:
  #     - name: GrailMarket
  #       address: 0x17219F4a8C82fb155eCFe0933DaC8019B248dF43
  - id: 2818 # Morph
    rpc_config:
      url: https://rpc.morphl2.io
    start_block: 10422622
    contracts:
      - name: GrailMarket
        address: 0xAc4F7F2E3f2EB476Ca65F3036230a0A44b457c3d
  - id: 10 # Optimism
    start_block: 136086315
    contracts:
      - name: GrailMarket
        address: 0xAc4F7F2E3f2EB476Ca65F3036230a0A44b457c3d
  - id: 137 # Polygon
    start_block: 71761331
    contracts:
      - name: GrailMarket
        address: 0xb9b367969De3b871686f07aD75f60Ae36D812121
  - id: 534352 # Scroll
    start_block: 15693727
    contracts:
      - name: GrailMarket
        address: 0x9C13F708FcDB955eD53497B6D107994EF6A02aed
  - id: 1329 # SEI
    rpc_config:
      url: https://sei.drpc.org
    start_block: 148272186
    contracts:
      - name: GrailMarket
        address: 0x66c4e441B38877110B07BD16788E2f20F9dfFD9D
  - id: 146 # Sonic
    rpc_config:
      url: https://sonic-rpc.publicnode.com
    start_block: 28320438
    contracts:
      - name: GrailMarket
        address: 0x50096e53E0C6e0d124863Dc7f7997fD55B784f62
  # - id: 1868 # Soneium
  #   rpc_config:
  #     url: https://rpc.soneium.org
  #   start_block: 6138154
  #   contracts:
  #     - name: GrailMarket
  #       address: 0x4A203f5Fc6AbDe7978A4A45531D0BE30678A3efB
  - id: 167000 # Taiko
    rpc_config:
      url: https://taiko-rpc.publicnode.com
    start_block: 1164440
    contracts:
      - name: GrailMarket
        address: 0x66c4e441B38877110B07BD16788E2f20F9dfFD9D
  - id: 10143 # Monad Testnet
    rpc_config:
      url: https://testnet-rpc.monad.xyz
    start_block: 17768926
    contracts:
      - name: GrailMarket
        address: 0xdB823E2858Df1Ce876c8A200DEE9bef30f6C29Ea
# Rollback on reorg mode currently incurs a performance hit on historical sync
# while developing an indexer we recommend setting this to false
rollback_on_reorg: false
