# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: PredictionMarket
description: Grail market indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
  - name: PredictionMarket
    abi_file_path: ./abis/PredictionMarketAbi.json
    handler: ./src/EventHandlers.ts
    events:
      - event: Bearish(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: Bullish(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: Settle(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 reward)
      - event: ClaimRefund(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: CreateMarket(bytes32 indexed id, address creator)
      - event: SetMinStakeAmount(uint256 minStakeAmount)
      - event: NewRound(bytes32 indexed id, uint256 indexed roundId, uint256 openingTime, uint256 closingTime)
      - event: SetRoundPriceMark(bytes32 indexed id, uint256 indexed roundId, int256 priceMark, uint256 closingTime)
      - event: Resolve(bytes32 indexed id, uint256 indexed roundId, uint256 rewardPool, uint256 totalWinningStake, int256 closingPrice, uint256 winningSide, bool isRefunding)
      - event: CancelRound(bytes32 indexed id, uint256 indexed roundId)
      - event: SetMarketDuration(uint32 duration)
      - event: OwnershipTransferred(address indexed oldOwner, address indexed newOwner)
      - event: SetResolverFee(uint16 newFee)
      - event: event SetProtocolFee(uint16 newFee)
unordered_multichain_mode: true
networks:
  - id: 296 # Hedera Testnet
    rpc_config:
      url: https://testnet.hashio.io/api
    start_block: 13084586
    contracts:
      - name: PredictionMarket #A reference to the global contract definition
        address: 0x9C13F708FcDB955eD53497B6D107994EF6A02aed
  - id: 2810 # Morph Testnet
    start_block: 14208953
    contracts:
      - name: PredictionMarket #A reference to the global contract definition
        address: 0xc346d6e45C24593aa49EAbA57F7268f32b044238
  - id: 534351 # Scroll Sepolia
    rpc_config:
      url: https://scroll-sepolia-rpc.publicnode.com
    start_block: 7549038
    contracts:
      - name: PredictionMarket #A reference to the global contract definition
        address: 0xb286f40F00c45964af8196eFeF5dB41ED2F014CB
  - id: 167009 # Taiko Hekla
    rpc_config:
      url: https://taiko-hekla.drpc.org
    start_block: 1046450
    contracts:
      - name: PredictionMarket #A reference to the global contract definition
        address: 0x61e8FC5D6be8DcA10Bc9aDC793FcA8DEadA6B29A
  - id: 1301 # Unichain Sepolia
    start_block: 7339649
    contracts:
      - name: PredictionMarket #A reference to the global contract definition
        address: 0x8A79d1a2d3D0492Cd1cf4dAd01bA20a661F672F4
# Rollback on reorg mode currently incurs a performance hit on historical sync
# while developing an indexer we recommend setting this to false
rollback_on_reorg: false
