# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: PredictionMarket
description: Grail market indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
  - name: PredictionMarket
    abi_file_path: ./abis/PredictionMarketAbi.json
    handler: ./src/EventHandlers.ts
    events:
      - event: Bearish(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: Bullish(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: Settle(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 reward)
      - event: ClaimRefund(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: CreateMarket(bytes32 indexed id, address creator)
      - event: SetMinStakeAmount(uint256 minStakeAmount)
      - event: NewRound(bytes32 indexed id, uint256 indexed roundId, uint256 openingTime, uint256 closingTime)
      - event: SetRoundPriceMark(bytes32 indexed id, uint256 indexed roundId, int256 priceMark, uint256 closingTime)
      - event: Resolve(bytes32 indexed id, uint256 indexed roundId, uint256 rewardPool, uint256 totalWinningStake, int256 closingPrice, uint256 winningSide, bool isRefunding)
      - event: CancelRound(bytes32 indexed id, uint256 indexed roundId)
      - event: SetMarketDuration(uint32 duration)
      - event: OwnershipTransferred(address indexed oldOwner, address indexed newOwner)
      - event: SetResolverFee(uint16 newFee)
      - event: event SetProtocolFee(uint16 newFee)
unordered_multichain_mode: true
networks:
  - id: 296 # Hedera Testnet
    rpc_config:
      url: https://testnet.hashio.io/api
    start_block: 12340027
    contracts:
      - name: PredictionMarket #A reference to the global contract definition
        address: 0xFb83f2edEA044580942F9a47e77D3cA8C89061c0
  - id: 2810 # Morph Testnet
    start_block: 13674578
    contracts:
      - name: PredictionMarket #A reference to the global contract definition
        address: 0x2cB48ab09b7AE3917cC2f905e541464d0f223827
  - id: 534351 # Scroll Sepolia
    rpc_config:
      url: https://scroll-sepolia-rpc.publicnode.com
    start_block: 7397443
    contracts:
      - name: PredictionMarket #A reference to the global contract definition
        address: 0x89b710b7CD5f5a35913278b6A280338b8209f466
  - id: 167009 # Taiko Hekla
    rpc_config:
      url: https://taiko-hekla.drpc.org
    start_block: 1004451
    contracts:
      - name: PredictionMarket #A reference to the global contract definition
        address: 0x50096e53E0C6e0d124863Dc7f7997fD55B784f62
  - id: 1301 # Unichain Sepolia
    start_block: 5842382
    contracts:
      - name: PredictionMarket #A reference to the global contract definition
        address: 0x66c4e441B38877110B07BD16788E2f20F9dfFD9D
# Rollback on reorg mode currently incurs a performance hit on historical sync
# while developing an indexer we recommend setting this to false
rollback_on_reorg: false
