# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: PredictionMarket
description: Grail market indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
  - name: PredictionMarket
    abi_file_path: ./abis/PredictionMarketAbi.json
    handler: ./src/EventHandlers.ts
    events:
      - event: Bearish(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: Bullish(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: Settle(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 reward)
      - event: ClaimRefund(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: CreateMarket(bytes32 indexed id, bytes32 indexed oracleId, address indexed creator, uint256 duration)
      - event: SetMinStakeAmount(bytes32 indexed id, uint256 minStakeAmount)
      - event: NewRound(bytes32 indexed id, uint256 indexed roundId, uint256 openingTime, uint256 closingTime)
      - event: SetRoundPriceMark(bytes32 indexed id, uint256 indexed roundId, int256 priceMark, uint256 closingTime)
      - event: SettleRound(bytes32 indexed id, uint256 indexed roundId, uint256 rewardPool, uint256 totalWinningStake, int256 closingPrice, bool isRefunding)
      - event: CancelRound(bytes32 indexed id, uint256 indexed roundId)
      - event: SetMarketDuration(bytes32 indexed id, uint32 duration)
      - event: Pause(bytes32 indexed id)
      - event: UnPause(bytes32 indexed id)
networks:
  - id: 137 # Polygon
    start_block: 45336336
    contracts:
      - name: PredictionMarket #A reference to the global contract definition
        address: 0x9D02A17dE4E68545d3a58D3a20BbBE0399E05c9c
  - id: 59144 # Linea
    start_block: 367801
    contracts:
      - name: PredictionMarket #A reference to the global contract definition
        address: 0xdEe21B97AB77a16B4b236F952e586cf8408CF32A
# Rollback on reorg mode currently incurs a performance hit on historical sync
# while developing an indexer we recommend setting this to false
rollback_on_reorg: false
