# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: GrailMarket
description: Grail market crosschain indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
  - name: GrailMarket
    abi_file_path: ./abis/GrailMarketAbi.json
    handler: ./src/EventHandlers.ts
    events:
      - event: Bearish(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: Bullish(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: Settle(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 reward)
      - event: ClaimRefund(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: CreateMarket(bytes32 indexed id, address creator)
      - event: SetMinStakeAmount(uint256 minStakeAmount)
      - event: NewRound(bytes32 indexed id, uint256 indexed roundId, uint256 openingTime, uint256 closingTime)
      - event: SetRoundPriceMark(bytes32 indexed id, uint256 indexed roundId, int256 priceMark, uint256 closingTime)
      - event: Resolve(bytes32 indexed id, uint256 indexed roundId, uint256 rewardPool, uint256 totalWinningStake, int256 closingPrice, uint256 winningSide, bool isRefunding)
      - event: CancelRound(bytes32 indexed id, uint256 indexed roundId)
      - event: SetMarketDuration(uint32 duration)
      - event: OwnershipTransferred(address indexed oldOwner, address indexed newOwner)
      - event: SetProtocolFee(uint16 newFee)
      # - event: BridgeBalance(uint16 indexed targetChain, uint256 amount)
      # - event: BridgeDeposit(uint16 indexed sourceChain, address indexed depositor, uint256 amount)
      # - event: Deposit(address indexed depositor, uint256 amount)
      # - event: Cashout(address indexed recipient, uint256 amount)
unordered_multichain_mode: true
networks:
  - id: 43113 # Avalanche Fuji Testnet
    start_block: 37478294
    contracts:
      - name: GrailMarket #A reference to the global contract definition
        address: 0x15d3C80Ee994804317bc29d431D4dbB0786CCD57
  - id: 11155111 # Ethereum Sepolia Testnet
    start_block: 7455379
    contracts:
      - name: GrailMarket #A reference to the global contract definition
        address: 0x66a26Ecb5F71A98F820504fd10deeC4aB9D52163
  - id: 11155420 # Optimism Sepolia
    start_block: 22322191
    contracts:
      - name: GrailMarket #A reference to the global contract definition
        address: 0x3AA3e6B100c7F7Cac63A82c1629613ACB924d68B
  - id: 84532 # Base Sepolia
    start_block: 20342984
    contracts:
      - name: GrailMarket #A reference to the global contract definition
        address: 0x3AA3e6B100c7F7Cac63A82c1629613ACB924d68B
  - id: 97 # BSC Testnet
    start_block: 47240546
    contracts:
      - name: GrailMarket #A reference to the global contract definition
        address: 0x8dd69d80170a58265e9FA9919e29F43cc7CE6936
# Rollback on reorg mode currently incurs a performance hit on historical sync
# while developing an indexer we recommend setting this to false
rollback_on_reorg: false
