# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: GrailMarket
description: Grail market crosschain indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
  - name: GrailMarket
    abi_file_path: ./abis/GrailMarketAbi.json
    handler: ./src/EventHandlers.ts
    events:
      - event: Bearish(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: Bullish(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: Settle(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 reward)
      - event: ClaimRefund(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: CreateMarket(bytes32 indexed id, address creator)
      - event: SetMinStakeAmount(uint256 minStakeAmount)
      - event: NewRound(bytes32 indexed id, uint256 indexed roundId, uint256 openingTime, uint256 closingTime)
      - event: SetRoundPriceMark(bytes32 indexed id, uint256 indexed roundId, int256 priceMark, uint256 closingTime)
      - event: Resolve(bytes32 indexed id, uint256 indexed roundId, uint256 rewardPool, uint256 totalWinningStake, int256 closingPrice, uint256 winningSide, bool isRefunding)
      - event: CancelRound(bytes32 indexed id, uint256 indexed roundId)
      - event: SetMarketDuration(uint32 duration)
      - event: OwnershipTransferred(address indexed oldOwner, address indexed newOwner)
      - event: SetResolverFee(uint16 newFee)
      - event: SetProtocolFee(uint16 newFee)
      - event: Rebalance(uint16 indexed fromChainId, uint16 indexed toChainId, address from, address to, uint256 amount)
      - event: ReceiveBalance(uint16 indexed fromChainId, uint256 amount)
      - event: BridgeBalance(uint16 indexed targetChain, uint256 amount)
      - event: BridgeDeposit(uint16 indexed sourceChain, address indexed depositor, uint256 amount)
      - event: Deposit(address indexed depositor, uint256 amount)
      - event: Cashout(address indexed recipient, uint256 amount)
unordered_multichain_mode: true
networks:
  - id: 43113 # Avalanche Fuji Testnet
    start_block: 12340027
    contracts:
      - name: GrailMarket #A reference to the global contract definition
        address: 0xFb83f2edEA044580942F9a47e77D3cA8C89061c0
  - id: 11155111 # Ethereum Sepolia Testnet
    start_block: 13674578
    contracts:
      - name: GrailMarket #A reference to the global contract definition
        address: 0x2cB48ab09b7AE3917cC2f905e541464d0f223827
  - id: 80002 # Polygon Amoy Testnet
    start_block: 7397443
    contracts:
      - name: GrailMarket #A reference to the global contract definition
        address: 0x89b710b7CD5f5a35913278b6A280338b8209f466
  - id: 421614 # Arbitrum Sepolia
    start_block: 1004451
    contracts:
      - name: GrailMarket #A reference to the global contract definition
        address: 0x50096e53E0C6e0d124863Dc7f7997fD55B784f62
  - id: 11155420 # Optimism Sepolia
    start_block: 5842382
    contracts:
      - name: GrailMarket #A reference to the global contract definition
        address: 0x66c4e441B38877110B07BD16788E2f20F9dfFD9D
  - id: 84532 # Base Sepolia
    start_block: 5842382
    contracts:
      - name: GrailMarket #A reference to the global contract definition
        address: 0x66c4e441B38877110B07BD16788E2f20F9dfFD9D
  - id: 97 # BSC Testnet
    start_block: 5842382
    contracts:
      - name: GrailMarket #A reference to the global contract definition
        address: 0x66c4e441B38877110B07BD16788E2f20F9dfFD9D
# Rollback on reorg mode currently incurs a performance hit on historical sync
# while developing an indexer we recommend setting this to false
rollback_on_reorg: false
