# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: GrailMarket
description: Grail market crosschain indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
  - name: GrailMarket
    abi_file_path: ./abis/GrailMarketAbi.json
    handler: ./src/EventHandlers.ts
    events:
      - event: Bearish(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: Bullish(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 stake)
      - event: Settle(bytes32 indexed id, uint256 indexed roundId, address indexed account, bytes32 positionId, uint256 reward, bool isRefund)
      - event: CreateMarket(bytes32 indexed id, address creator)
      - event: SetMinStakeAmount(uint256 minStakeAmount)
      - event: NewRound(bytes32 indexed id, uint256 indexed roundId, uint256 openingTime, uint256 closingTime, uint64 sequenceId)
      - event: SetRoundPriceMark(bytes32 indexed id, uint256 indexed roundId, int256 priceMark, uint256 closingTime)
      - event: Resolve(bytes32 indexed id, uint256 indexed roundId, uint256 rewardPool, uint256 totalWinningStake, int256 closingPrice, uint256 winningSide, uint64 sequenceId)
      - event: CancelRound(bytes32 indexed id, uint256 indexed roundId)
      - event: SetMarketDuration(uint32 duration)
      - event: SetProtocolFee(uint16 newFee)
unordered_multichain_mode: true
networks:
  - id: 43114 # Avalanche
    start_block: 63949727
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 42161 # Arbitrum
    start_block: 347938530
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 8453 # Base
    start_block: 31642231
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 81457 # Blast
    start_block: 20632021
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 56 # BNB
    rpc_config:
      url: https://bsc-dataseed2.bnbchain.org
    start_block: 51557147
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 1313161554 # Aurora
    start_block: 151351150
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 80094 # Berachain
    start_block: 6461833
    contracts:
      - name: GrailMarket
        address: 0x52eA8a14448302a6941327c719A593396df73BeC
  - id: 42220 # Celo
    rpc_config:
      url: https://forno.celo.org
    start_block: 38173182
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 1116 # Core
    rpc_config:
      url: https://rpc.coredao.org
    start_block: 25590213
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 25 # Cronos
    rpc_config:
      url: https://evm.cronos.org
    start_block: 20002726
    contracts:
      - name: GrailMarket
        address: 0x2d1B9c87216d1a6138f76E73F1d32cca8FeADb97
  - id: 100 # Gnosis
    start_block: 40613449
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 2818 # Morph
    rpc_config:
      url: https://rpc.morphl2.io
    start_block: 11003993
    contracts:
      - name: GrailMarket
        address: 0x4640294869A15C589faA1e81C65E3155E03ff009
  - id: 57073 # Ink
    rpc_config:
      url: https://rpc-qnd.inkonchain.com
    start_block: 16577699
    contracts:
      - name: GrailMarket
        address: 0x03dc4f4eD715c7b75A4e7dD1Bc6C7A41d4123e18
  - id: 10 # Optimism
    start_block: 137238979
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 137 # Polygon
    start_block: 72838832
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 130 # Unichain
    start_block: 19328490
    contracts:
      - name: GrailMarket
        address: 0xB08269B1984a981Ff111e4ab9cdf6BdeD2e16030
  - id: 1284 # Moonbeam
    rpc_config:
      url: https://rpc.api.moonbeam.network
    start_block: 11327992
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 59144 # Linea
    rpc_config:
      url: https://rpc.linea.build
    start_block: 20063679
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 169 # Manta
    rpc_config:
      url: https://manta-pacific.drpc.org
    start_block: 5585352
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 5000 # Mantle
    rpc_config:
      url: https://rpc.mantle.xyz
    start_block: 80973675
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 34443 # Mode
    rpc_config:
      url: https://mainnet.mode.network
    start_block: 24955113
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 204 # OpBNB
    rpc_config:
      url: https://opbnb-rpc.publicnode.com
    start_block: 63198076
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 534352 # Scroll
    rpc_config:
      url: https://rpc.scroll.io
    start_block: 16511716
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 146 # Sonic
    rpc_config:
      url: https://rpc.soniclabs.com
    start_block: 34318693
    contracts:
      - name: GrailMarket
        address: 0xB08269B1984a981Ff111e4ab9cdf6BdeD2e16030
  - id: 1868 # Sonieum
    rpc_config:
      url: https://rpc.soneium.org
    start_block: 8472016
    contracts:
      - name: GrailMarket
        address: 0x03dc4f4eD715c7b75A4e7dD1Bc6C7A41d4123e18
  - id: 167000 # Taiko
    rpc_config:
      url: https://taiko-rpc.publicnode.com
    start_block: 1209756
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 1329 # Sei
    rpc_config:
      url: https://sei.drpc.org
    start_block: 152539705
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 4200 # Merlin
    rpc_config:
      url: https://rpc.merlinchain.io
    start_block: 22344672
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
  - id: 480 # Worldchain
    rpc_config:
      url: https://worldchain-mainnet.g.alchemy.com/public
    start_block: 15373532
    contracts:
      - name: GrailMarket
        address: 0x4640294869A15C589faA1e81C65E3155E03ff009
  - id: 196 # XLayer
    rpc_config:
      url: https://rpc.xlayer.tech
    start_block: 18297607
    contracts:
      - name: GrailMarket
        address: 0x27FFd98bF28Bef70e1297a051e589248BBa9F00d
# Rollback on reorg mode currently incurs a performance hit on historical sync
# while developing an indexer we recommend setting this to false
rollback_on_reorg: false
